### ISSUE TITLE
error in installing the service

### ISSUE THREAD

**Issue by luluprat** [abajwa-hw/opentsdb-service#1]
hello i have this error in the ambari add service:
Error
500 status code received on GET method for API: /api/v1/stacks/HDP/versions/2.2/validations 

Error message: KeyError: 'hbase_regionserver_heapsize'

what may i do ?
thanks

**Comment by abajwa-hw** [comment]
Hi you can ignore this warning and proceed with installation. It will be fixed in upcoming revision to sandbox. You can find more details about this and other known issues in the sandbox release notes:
http://hortonworks.com/wp-content/uploads/2015/04/ReleaseNotes_4_17_2015.pdf

On May 6, 2015, at 8:24 AM, luluprat <notifications@github.com<mailto:notifications@github.com>> wrote:

hello i have this error in the ambari add service:
Error
500 status code received on GET method for API: /api/v1/stacks/HDP/versions/2.2/validations

Error message: KeyError: 'hbase_regionserver_heapsize'

what may i do ?
thanks
